spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-feng-dev
---
spring:
  profiles: test #测试黄精
  application:
    name: microservicecloud-config-feng-test
#请保存为utf-8
